/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author helia
 */
import java.util.ArrayList;

public class FenetreQuiz extends javax.swing.JFrame {

    private int scoreCourant = 0;
    private int indexQuestionCourante = 0;
    private ArrayList<Question> questions;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FenetreQuiz.class.getName());

    /**
     * Creates new form FenetreQuiz
     */
    public FenetreQuiz() {
        initComponents();
        btnRep1.setText("Hello");
        btnRep2.setText("Hello");
        btnRep3.setText("Hello");
        btnRep4.setText("Hello");
        questions = new ArrayList<>();

        Question q1 = new Question("Quelle est la capitale de la France ?", "Paris", "Londres", "Berlin", "Madrid", 1);

        Question q2 = new Question("Combien font 5 x 6 ?", "25", "30", "35", "40", 2);

        Question q3 = new Question("Quel est le plus grand océan ?", "Atlantique", "Indien", "Pacifique", "Arctique", 3);

        Question q4 = new Question("Combien de continents existe-t-il ?", "5", "6", "7", "8", 3);

        Question q5 = new Question("Quelle planète est la plus proche du Soleil ?", "Mercure", "Vénus", "Terre", "Mars", 1);

        Question q6 = new Question("En quelle année a débuté la Première Guerre mondiale ?", "1914", "1918", "1939", "1945", 1);

        Question q7 = new Question("Quel animal est le plus rapide sur terre ?", "Lion", "Guépard", "Antilope", "Cheval", 2);

        Question q8 = new Question("Combien de joueurs dans une équipe de football ?", "9", "10", "11", "12", 3);

        Question q9 = new Question("Quel langage est utilisé pour créer des pages web ?", "Python", "HTML", "Java", "C++", 2);

        Question q10 = new Question("Combien de jours compte une année bissextile ?", "364", "365", "366", "367", 3);
        questions.add(q1);
        questions.add(q2);
        questions.add(q3);
        questions.add(q4);
        questions.add(q5);
        questions.add(q6);
        questions.add(q7);
        questions.add(q8);
        questions.add(q9);
        questions.add(q10);

        afficherQuestionCourante();
    }

    private void afficherQuestionCourante() {
        btnNextQuestion.setEnabled(false);
        Question q = questions.get(indexQuestionCourante);
        lblQuestion.setText(q.getIntitule());
        btnRep1.setText(q.getProposition1());
        btnRep2.setText(q.getProposition2());
        btnRep3.setText(q.getProposition3());
        btnRep4.setText(q.getProposition4());
        btnRep1.setEnabled(true);
        btnRep2.setEnabled(true);
        btnRep3.setEnabled(true);
        btnRep4.setEnabled(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuestion = new javax.swing.JLabel();
        btnRep1 = new javax.swing.JButton();
        btnRep2 = new javax.swing.JButton();
        btnRep3 = new javax.swing.JButton();
        btnRep4 = new javax.swing.JButton();
        lblFeedback = new javax.swing.JLabel();
        btnNextQuestion = new javax.swing.JButton();
        lblScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblQuestion.setText("question");

        btnRep1.setText("Réponse 1 :");
        btnRep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep1ActionPerformed(evt);
            }
        });

        btnRep2.setText("Réponse 2 :");
        btnRep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep2ActionPerformed(evt);
            }
        });

        btnRep3.setText("Réponse 3 : ");
        btnRep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep3ActionPerformed(evt);
            }
        });

        btnRep4.setText("Réponse 4 :");
        btnRep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRep4ActionPerformed(evt);
            }
        });

        lblFeedback.setText("feedback");

        btnNextQuestion.setText("question suivante");
        btnNextQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextQuestionActionPerformed(evt);
            }
        });

        lblScore.setText("score courant");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(btnNextQuestion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(lblScore))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(lblQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFeedback, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRep1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRep2)
                        .addGap(18, 18, 18)
                        .addComponent(btnRep3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRep4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblQuestion)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRep1)
                    .addComponent(btnRep2)
                    .addComponent(btnRep3)
                    .addComponent(btnRep4))
                .addGap(29, 29, 29)
                .addComponent(lblFeedback)
                .addGap(28, 28, 28)
                .addComponent(btnNextQuestion)
                .addGap(26, 26, 26)
                .addComponent(lblScore)
                .addContainerGap(351, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextQuestionActionPerformed

        indexQuestionCourante++;
        if (indexQuestionCourante < questions.size()) {
            afficherQuestionCourante();

        } else {
            lblScore.setText("Quiz terminé Score : " + scoreCourant + " / " + indexQuestionCourante);
            btnNextQuestion.setEnabled(false);
        }


    }//GEN-LAST:event_btnNextQuestionActionPerformed

    private void btnRep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep1ActionPerformed

        int reponseChoisie = 1;
        Question questionCourante = questions.get(indexQuestionCourante);
        if (reponseChoisie == questionCourante.getIndexBonneReponse()) {
            lblFeedback.setText("Bonne réponse !");
            scoreCourant++;
            lblScore.setText("Score : " + scoreCourant);
        } else {
            lblFeedback.setText("Mauvaise réponse !");

        }
        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
        btnNextQuestion.setEnabled(true);
    }//GEN-LAST:event_btnRep1ActionPerformed

    private void btnRep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep2ActionPerformed
   
        int reponseChoisie = 2;
        Question questionCourante = questions.get(indexQuestionCourante);
        if (reponseChoisie == questionCourante.getIndexBonneReponse()) {
            lblFeedback.setText("Bonne réponse !");
            scoreCourant++;
            lblScore.setText("Score : " + scoreCourant);
        } else {
            lblFeedback.setText("Mauvaise réponse !");

        }
        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
        btnNextQuestion.setEnabled(true);
    }//GEN-LAST:event_btnRep2ActionPerformed

    private void btnRep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep3ActionPerformed
      
        int reponseChoisie = 3;
        Question questionCourante = questions.get(indexQuestionCourante);
        if (reponseChoisie == questionCourante.getIndexBonneReponse()) {
            lblFeedback.setText("Bonne réponse !");
            scoreCourant++;
            lblScore.setText("Score : " + scoreCourant);
        } else {

        }
        lblFeedback.setText("Mauvaise réponse !");
        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
        btnNextQuestion.setEnabled(true);
    }//GEN-LAST:event_btnRep3ActionPerformed

    private void btnRep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRep4ActionPerformed
        
        int reponseChoisie = 4;
        Question questionCourante = questions.get(indexQuestionCourante);
        if (reponseChoisie == questionCourante.getIndexBonneReponse()) {
            lblFeedback.setText("Bonne réponse !");
            scoreCourant++;
            lblScore.setText("Score : " + scoreCourant);
        } else {
            lblFeedback.setText("Mauvaise réponse !");

        }
        btnRep1.setEnabled(false);
        btnRep2.setEnabled(false);
        btnRep3.setEnabled(false);
        btnRep4.setEnabled(false);
        btnNextQuestion.setEnabled(true);
    }//GEN-LAST:event_btnRep4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FenetreQuiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNextQuestion;
    private javax.swing.JButton btnRep1;
    private javax.swing.JButton btnRep2;
    private javax.swing.JButton btnRep3;
    private javax.swing.JButton btnRep4;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JLabel lblScore;
    // End of variables declaration//GEN-END:variables

}
