/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author helia
 */
public class fenetre_cadenas extends javax.swing.JFrame {
    private int nbCourant0;
    private int nbCourant1;
    private int nbCourant2;
    private int nbCourant3;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(fenetre_cadenas.class.getName());

    /**
     * Creates new form fenetre_cadenas
     */
    public fenetre_cadenas() {
        initComponents();
        chiffres a = new chiffres();
        a.chiffreAleat();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        texte_intro = new javax.swing.JLabel();
        texte_chiffre_0 = new javax.swing.JLabel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        bouton_tester = new javax.swing.JButton();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_chiffres_haut = new javax.swing.JLabel();
        texte_score = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_lbl_chiffres_bas = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        up_chiffre_4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            getContentPane().add(up_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

            up_chiffre_2.setText("/\\");
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                getContentPane().add(up_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 80, -1));

                up_chiffre_3.setText("/\\");
                    up_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            up_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(up_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 80, -1));

                    down_chiffre_1.setText("\\/");
                    down_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            down_chiffre_1ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(down_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 75, -1));

                    down_chiffre_2.setText("\\/");
                    down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            down_chiffre_2ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(down_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 75, -1));

                    down_chiffre_3.setText("\\/");
                    down_chiffre_3.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            down_chiffre_3ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(down_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 75, -1));

                    down_chiffre_4.setText("\\/");
                    down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            down_chiffre_4ActionPerformed(evt);
                        }
                    });
                    getContentPane().add(down_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 75, -1));

                    texte_intro.setText("Trouvez le bon code en moins de 5 tentatives ! ");
                    getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 6, 305, -1));

                    texte_chiffre_0.setText("0");
                    getContentPane().add(texte_chiffre_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 142, 20, -1));

                    texte_chiffre_1.setText("1");
                    getContentPane().add(texte_chiffre_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 20, -1));

                    texte_chiffre_2.setText("2");
                    getContentPane().add(texte_chiffre_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 20, -1));

                    texte_chiffre_3.setText("3");
                    getContentPane().add(texte_chiffre_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 20, -1));

                    bouton_tester.setText("Tester");
                    bouton_tester.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            bouton_testerActionPerformed(evt);
                        }
                    });
                    getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, -1, -1));

                    texte_lbl_nb_chiffres_exacts.setText("Nombre de chiffres exacts : ");
                    getContentPane().add(texte_lbl_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

                    texte_nb_chiffres_exacts.setText("0");
                    getContentPane().add(texte_nb_chiffres_exacts, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, -1, -1));

                    texte_lbl_chiffres_haut.setText("Nombre de chiffres trop hauts : ");
                    getContentPane().add(texte_lbl_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, 20));

                    texte_score.setText("0 sur 5");
                    getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

                    texte_tentatives.setText("Tentatives");
                    getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, -1));

                    bouton_recommencer.setText("Recommencer");
                    bouton_recommencer.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            bouton_recommencerActionPerformed(evt);
                        }
                    });
                    getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, -1, -1));

                    texte_lbl_nb_chiffres_haut.setText("0");
                    getContentPane().add(texte_lbl_nb_chiffres_haut, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

                    texte_lbl_chiffres_bas.setText("Nombre de chiffres trop bas : ");
                    getContentPane().add(texte_lbl_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

                    texte_lbl_nb_chiffres_bas.setText("0");
                    getContentPane().add(texte_lbl_nb_chiffres_bas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

                    up_chiffre_4.setText("/\\");
                        up_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                up_chiffre_4ActionPerformed(evt);
                            }
                        });
                        getContentPane().add(up_chiffre_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 80, -1));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        if(nbCourant0<9){
           nbCourant0++;
        }
        else {
                   nbCourant0=0;
                   }
        texte_chiffre_0.setText(nbCourant0+ "");
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void down_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_1ActionPerformed
        if(nbCourant0>0){
           nbCourant0--;
        }
        else {
                   nbCourant0=9;
                   }
        texte_chiffre_0.setText(nbCourant0+ "");
    }//GEN-LAST:event_down_chiffre_1ActionPerformed

    private void up_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_3ActionPerformed
        if(nbCourant2<9){
           nbCourant2++;
        }
        else {
                   nbCourant2=0;
                   }
        texte_chiffre_2.setText(nbCourant2+ "");
    }//GEN-LAST:event_up_chiffre_3ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        if(nbCourant1<9){
           nbCourant1++;
        }
        else {
                   nbCourant1=0;
                   }
        texte_chiffre_1.setText(nbCourant1+ "");
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        if(nbCourant1>0){
           nbCourant1--;
        }
        else {
                   nbCourant1=9;
                   }
        texte_chiffre_1.setText(nbCourant1+ "");
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    private void down_chiffre_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_3ActionPerformed
        if(nbCourant2>0){
           nbCourant2--;
        }
        else {
                   nbCourant2=9;
                   }
        texte_chiffre_2.setText(nbCourant2+ "");
    }//GEN-LAST:event_down_chiffre_3ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        if(nbCourant3>0){
           nbCourant3--;
        }
        else {
                   nbCourant3=9;
                   }
        texte_chiffre_3.setText(nbCourant3+ "");
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void bouton_testerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_testerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_testerActionPerformed

    private void bouton_recommencerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bouton_recommencerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bouton_recommencerActionPerformed

    private void up_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_4ActionPerformed
        if(nbCourant3<9){
           nbCourant3++;
        }
        else {
                   nbCourant3=0;
                   }
        texte_chiffre_3.setText(nbCourant3+ "");
    }//GEN-LAST:event_up_chiffre_4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new fenetre_cadenas().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JLabel texte_chiffre_0;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_chiffres_bas;
    private javax.swing.JLabel texte_lbl_chiffres_haut;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables
}
